"""empty message

Revision ID: 046e87a52cc5
Revises: None
Create Date: 2016-10-03 17:49:41.330474

"""

# revision identifiers, used by Alembic.
revision = '046e87a52cc5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_province',
    sa.Column('ctxp_id', sa.Integer(), nullable=False),
    sa.Column('ctxp_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ctxp_id')
    )
    op.create_table('cartix_district',
    sa.Column('ctxd_id', sa.Integer(), nullable=False),
    sa.Column('ctxd_name', sa.String(length=20), nullable=True),
    sa.Column('ctxp_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxp_province'], ['cartix_province.ctxp_id'], ),
    sa.PrimaryKeyConstraint('ctxd_id')
    )
    op.create_table('cartix_sector',
    sa.Column('ctxs_id', sa.Integer(), nullable=False),
    sa.Column('ctxs_name', sa.String(length=50), nullable=True),
    sa.Column('ctxd_district', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxd_district'], ['cartix_district.ctxd_id'], ),
    sa.PrimaryKeyConstraint('ctxs_id')
    )
    op.create_table('cartix_agent',
    sa.Column('ctxa_id', sa.Integer(), nullable=False),
    sa.Column('ctxa_name', sa.String(length=50), nullable=True),
    sa.Column('ctxa_type', sa.String(length=50), nullable=True),
    sa.Column('ctxa_sector', sa.Integer(), nullable=True),
    sa.Column('ctxa_district', sa.Integer(), nullable=True),
    sa.Column('ctxa_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxa_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxa_province'], ['cartix_province.ctxp_id'], ),
    sa.ForeignKeyConstraint(['ctxa_sector'], ['cartix_sector.ctxs_id'], ),
    sa.PrimaryKeyConstraint('ctxa_id')
    )
    op.create_table('cartix_financial_inst',
    sa.Column('ctxfn_id', sa.Integer(), nullable=False),
    sa.Column('ctxfn_name', sa.String(length=50), nullable=True),
    sa.Column('ctxfn_type', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_sector', sa.Integer(), nullable=True),
    sa.Column('ctxsg_district', sa.Integer(), nullable=True),
    sa.Column('ctxsg_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxsg_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxsg_province'], ['cartix_province.ctxp_id'], ),
    sa.ForeignKeyConstraint(['ctxsg_sector'], ['cartix_sector.ctxs_id'], ),
    sa.PrimaryKeyConstraint('ctxfn_id')
    )
    op.create_table('cartix_population',
    sa.Column('ctxpp_id', sa.Integer(), nullable=False),
    sa.Column('ctxpp_name', sa.String(length=50), nullable=True),
    sa.Column('ctxpp_total', sa.Integer(), nullable=True),
    sa.Column('ctxpp_male', sa.Integer(), nullable=True),
    sa.Column('ctxpp_female', sa.Integer(), nullable=True),
    sa.Column('ctxpp_province', sa.Integer(), nullable=True),
    sa.Column('ctxpp_district', sa.Integer(), nullable=True),
    sa.Column('ctxpp_sector', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxpp_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxpp_province'], ['cartix_province.ctxp_id'], ),
    sa.ForeignKeyConstraint(['ctxpp_sector'], ['cartix_sector.ctxs_id'], ),
    sa.PrimaryKeyConstraint('ctxpp_id')
    )
    op.create_table('cartix_savinggroup',
    sa.Column('ctxsg_id', sa.Integer(), nullable=False),
    sa.Column('ctxsg_name', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_creationyear', sa.Integer(), nullable=True),
    sa.Column('ctxsg_sector', sa.Integer(), nullable=True),
    sa.Column('ctxsg_district', sa.Integer(), nullable=True),
    sa.Column('ctxsg_province', sa.Integer(), nullable=True),
    sa.Column('ctxsg_members', sa.Integer(), nullable=True),
    sa.Column('ctxsg_female', sa.Integer(), nullable=True),
    sa.Column('ctxsg_male', sa.Integer(), nullable=True),
    sa.Column('ctxsg_fundingNgo', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_partnerNgo', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_amount', sa.Integer(), nullable=True),
    sa.Column('ctxsg_outstLoan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxsg_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxsg_province'], ['cartix_province.ctxp_id'], ),
    sa.ForeignKeyConstraint(['ctxsg_sector'], ['cartix_sector.ctxs_id'], ),
    sa.PrimaryKeyConstraint('ctxsg_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_savinggroup')
    op.drop_table('cartix_population')
    op.drop_table('cartix_financial_inst')
    op.drop_table('cartix_agent')
    op.drop_table('cartix_sector')
    op.drop_table('cartix_district')
    op.drop_table('cartix_province')
    ### end Alembic commands ###
