"""empty message

Revision ID: 078848f3b74d
Revises: d29ca6054018
Create Date: 2016-10-24 15:58:43.610953

"""

# revision identifiers, used by Alembic.
revision = '078848f3b74d'
down_revision = 'd29ca6054018'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_bankagent',
    sa.Column('ctxba_id', sa.Integer(), nullable=False),
    sa.Column('ctxba_count', sa.Integer(), nullable=True),
    sa.Column('ctxba_district', sa.Integer(), nullable=True),
    sa.Column('ctxba_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxba_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxba_province'], ['cartix_province.ctxp_id'], ),
    sa.PrimaryKeyConstraint('ctxba_id')
    )
    op.create_table('cartix_telcoagent',
    sa.Column('ctxa_id', sa.Integer(), nullable=False),
    sa.Column('ctxa_count', sa.Integer(), nullable=True),
    sa.Column('ctxa_district', sa.Integer(), nullable=True),
    sa.Column('ctxa_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxa_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxa_province'], ['cartix_province.ctxp_id'], ),
    sa.PrimaryKeyConstraint('ctxa_id')
    )
    op.drop_table('cartix_agent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_agent',
    sa.Column('ctxa_id', sa.INTEGER(), nullable=False),
    sa.Column('ctxa_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ctxa_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ctxa_sector', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxa_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxa_province', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ctxa_district'], [u'cartix_district.ctxd_id'], name=u'cartix_agent_ctxa_district_fkey'),
    sa.ForeignKeyConstraint(['ctxa_province'], [u'cartix_province.ctxp_id'], name=u'cartix_agent_ctxa_province_fkey'),
    sa.ForeignKeyConstraint(['ctxa_sector'], [u'cartix_sector.ctxs_id'], name=u'cartix_agent_ctxa_sector_fkey'),
    sa.PrimaryKeyConstraint('ctxa_id', name=u'cartix_agent_pkey')
    )
    op.drop_table('cartix_telcoagent')
    op.drop_table('cartix_bankagent')
    ### end Alembic commands ###
