"""empty message

Revision ID: 2354f56bd525
Revises: ce03bebc96b7
Create Date: 2016-10-26 10:45:39.330658

"""

# revision identifiers, used by Alembic.
revision = '2354f56bd525'
down_revision = 'ce03bebc96b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_telcoagent')
    op.drop_table('cartix_bankagent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_bankagent',
    sa.Column('ctxba_id', sa.INTEGER(), nullable=False),
    sa.Column('ctxba_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxba_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxba_province', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ctxba_district'], [u'cartix_district.ctxd_id'], name=u'cartix_bankagent_ctxba_district_fkey'),
    sa.ForeignKeyConstraint(['ctxba_province'], [u'cartix_province.ctxp_id'], name=u'cartix_bankagent_ctxba_province_fkey'),
    sa.PrimaryKeyConstraint('ctxba_id', name=u'cartix_bankagent_pkey')
    )
    op.create_table('cartix_telcoagent',
    sa.Column('ctxa_id', sa.INTEGER(), nullable=False),
    sa.Column('ctxa_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxa_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxa_province', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ctxa_district'], [u'cartix_district.ctxd_id'], name=u'cartix_telcoagent_ctxa_district_fkey'),
    sa.ForeignKeyConstraint(['ctxa_province'], [u'cartix_province.ctxp_id'], name=u'cartix_telcoagent_ctxa_province_fkey'),
    sa.PrimaryKeyConstraint('ctxa_id', name=u'cartix_telcoagent_pkey')
    )
    ### end Alembic commands ###
