"""empty message

Revision ID: 2a0877204fe5
Revises: e1237b819fd0
Create Date: 2016-10-24 17:59:22.759009

"""

# revision identifiers, used by Alembic.
revision = '2a0877204fe5'
down_revision = 'e1237b819fd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_mfi')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_mfi',
    sa.Column('ctxm_id', sa.INTEGER(), nullable=False),
    sa.Column('ctxm_province', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxm_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxm_sector', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxm_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ctxm_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ctxm_district'], [u'cartix_district.ctxd_id'], name=u'cartix_mfi_ctxm_district_fkey'),
    sa.ForeignKeyConstraint(['ctxm_province'], [u'cartix_province.ctxp_id'], name=u'cartix_mfi_ctxm_province_fkey'),
    sa.ForeignKeyConstraint(['ctxm_sector'], [u'cartix_sector.ctxs_id'], name=u'cartix_mfi_ctxm_sector_fkey'),
    sa.PrimaryKeyConstraint('ctxm_id', name=u'cartix_mfi_pkey')
    )
    ### end Alembic commands ###
