"""empty message

Revision ID: 2bc9a496ea5e
Revises: 1f5cfac41ad1
Create Date: 2016-10-26 11:40:23.594091

"""

# revision identifiers, used by Alembic.
revision = '2bc9a496ea5e'
down_revision = '1f5cfac41ad1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_bankagent',
    sa.Column('ctxba_id', sa.Integer(), nullable=False),
    sa.Column('ctxba_count', sa.Integer(), nullable=True),
    sa.Column('ctxba_district', sa.Integer(), nullable=True),
    sa.Column('ctxba_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxba_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxba_province'], ['cartix_province.ctxp_id'], ),
    sa.PrimaryKeyConstraint('ctxba_id')
    )
    op.create_table('cartix_telcoagent',
    sa.Column('ctxa_id', sa.Integer(), nullable=False),
    sa.Column('ctxa_count', sa.Integer(), nullable=True),
    sa.Column('ctxa_district', sa.Integer(), nullable=True),
    sa.Column('ctxa_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxa_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxa_province'], ['cartix_province.ctxp_id'], ),
    sa.PrimaryKeyConstraint('ctxa_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_telcoagent')
    op.drop_table('cartix_bankagent')
    ### end Alembic commands ###
