"""empty message

Revision ID: 3a368c52f951
Revises: 2a0877204fe5
Create Date: 2016-10-24 17:59:52.372604

"""

# revision identifiers, used by Alembic.
revision = '3a368c52f951'
down_revision = '2a0877204fe5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_mfi',
    sa.Column('ctxm_id', sa.Integer(), nullable=False),
    sa.Column('ctxm_province', sa.Integer(), nullable=True),
    sa.Column('ctxm_district', sa.Integer(), nullable=True),
    sa.Column('ctxm_sector', sa.Integer(), nullable=True),
    sa.Column('ctxm_name', sa.String(length=250), nullable=True),
    sa.Column('ctxm_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxm_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxm_province'], ['cartix_province.ctxp_id'], ),
    sa.ForeignKeyConstraint(['ctxm_sector'], ['cartix_sector.ctxs_id'], ),
    sa.PrimaryKeyConstraint('ctxm_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_mfi')
    ### end Alembic commands ###
