"""empty message

Revision ID: 43346fa88d24
Revises: 1821af9b0dbb
Create Date: 2016-10-24 11:18:25.207397

"""

# revision identifiers, used by Alembic.
revision = '43346fa88d24'
down_revision = '1821af9b0dbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartix_savinggroup', sa.Column('ctxsg_female', sa.Integer(), nullable=True))
    op.add_column('cartix_savinggroup', sa.Column('ctxsg_male', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartix_savinggroup', 'ctxsg_male')
    op.drop_column('cartix_savinggroup', 'ctxsg_female')
    ### end Alembic commands ###
