"""empty message

Revision ID: 748db30d9d69
Revises: b48ee05f7f59
Create Date: 2016-10-21 17:03:05.272532

"""

# revision identifiers, used by Alembic.
revision = '748db30d9d69'
down_revision = 'b48ee05f7f59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_savinggroup',
    sa.Column('ctxsg_id', sa.Integer(), nullable=False),
    sa.Column('ctxsg_name', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_creationyear', sa.Integer(), nullable=True),
    sa.Column('ctxsg_sector', sa.Integer(), nullable=True),
    sa.Column('ctxsg_district', sa.Integer(), nullable=True),
    sa.Column('ctxsg_province', sa.Integer(), nullable=True),
    sa.Column('ctxsg_members', sa.Integer(), nullable=True),
    sa.Column('ctxsg_female', sa.Integer(), nullable=True),
    sa.Column('ctxsg_male', sa.Integer(), nullable=True),
    sa.Column('ctxsg_fundingngo', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_partnerngo', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_status', sa.String(length=50), nullable=True),
    sa.Column('ctxsg_amount', sa.Integer(), nullable=True),
    sa.Column('ctxsg_outstloan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxsg_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxsg_province'], ['cartix_province.ctxp_id'], ),
    sa.ForeignKeyConstraint(['ctxsg_sector'], ['cartix_sector.ctxs_id'], ),
    sa.PrimaryKeyConstraint('ctxsg_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_savinggroup')
    ### end Alembic commands ###
