"""empty message

Revision ID: 7dc87eef1652
Revises: 2354f56bd525
Create Date: 2016-10-26 10:49:21.804066

"""

# revision identifiers, used by Alembic.
revision = '7dc87eef1652'
down_revision = '2354f56bd525'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_telcoagent',
    sa.Column('ctxa_id', sa.Integer(), nullable=False),
    sa.Column('ctxa_type', sa.String(length=50), nullable=True),
    sa.Column('ctxa_count', sa.Integer(), nullable=True),
    sa.Column('ctxa_district', sa.Integer(), nullable=True),
    sa.Column('ctxa_province', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ctxa_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxa_province'], ['cartix_province.ctxp_id'], ),
    sa.PrimaryKeyConstraint('ctxa_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_telcoagent')
    ### end Alembic commands ###
