"""empty message

Revision ID: 909da7f24d8a
Revises: 2bc9a496ea5e
Create Date: 2016-10-26 14:37:32.063503

"""

# revision identifiers, used by Alembic.
revision = '909da7f24d8a'
down_revision = '2bc9a496ea5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_bank')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_bank',
    sa.Column('ctxb_id', sa.INTEGER(), nullable=False),
    sa.Column('ctxb_province', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxb_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxb_sector', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxb_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ctxb_branches', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ctxb_district'], [u'cartix_district.ctxd_id'], name=u'cartix_bank_ctxb_district_fkey'),
    sa.ForeignKeyConstraint(['ctxb_province'], [u'cartix_province.ctxp_id'], name=u'cartix_bank_ctxb_province_fkey'),
    sa.ForeignKeyConstraint(['ctxb_sector'], [u'cartix_sector.ctxs_id'], name=u'cartix_bank_ctxb_sector_fkey'),
    sa.PrimaryKeyConstraint('ctxb_id', name=u'cartix_bank_pkey')
    )
    ### end Alembic commands ###
