"""empty message

Revision ID: 948177bfc6d0
Revises: 1eccebf02185
Create Date: 2016-10-04 14:22:03.217821

"""

# revision identifiers, used by Alembic.
revision = '948177bfc6d0'
down_revision = '1eccebf02185'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartix_population', 'ctxpp_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartix_population', sa.Column('ctxpp_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    ### end Alembic commands ###
