"""empty message

Revision ID: 9494cd02899b
Revises: 909da7f24d8a
Create Date: 2016-10-26 14:38:28.900624

"""

# revision identifiers, used by Alembic.
revision = '9494cd02899b'
down_revision = '909da7f24d8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_bank',
    sa.Column('ctxb_id', sa.Integer(), nullable=False),
    sa.Column('ctxb_province', sa.Integer(), nullable=True),
    sa.Column('ctxb_district', sa.Integer(), nullable=True),
    sa.Column('ctxb_sector', sa.Integer(), nullable=True),
    sa.Column('ctxb_name', sa.String(length=100), nullable=True),
    sa.Column('ctxb_branches', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ctxb_district'], ['cartix_district.ctxd_id'], ),
    sa.ForeignKeyConstraint(['ctxb_province'], ['cartix_province.ctxp_id'], ),
    sa.ForeignKeyConstraint(['ctxb_sector'], ['cartix_sector.ctxs_id'], ),
    sa.PrimaryKeyConstraint('ctxb_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_bank')
    ### end Alembic commands ###
