"""empty message

Revision ID: b48ee05f7f59
Revises: c1e15b8ede1d
Create Date: 2016-10-21 17:00:34.180768

"""

# revision identifiers, used by Alembic.
revision = 'b48ee05f7f59'
down_revision = 'c1e15b8ede1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartix_savinggroup')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartix_savinggroup',
    sa.Column('ctxsg_id', sa.INTEGER(), nullable=False),
    sa.Column('ctxsg_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ctxsg_creationyear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_sector', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_district', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_province', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_members', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_female', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_male', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_fundingNgo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ctxsg_partnerNgo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ctxsg_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_outstLoan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctxsg_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ctxsg_district'], [u'cartix_district.ctxd_id'], name=u'cartix_savinggroup_ctxsg_district_fkey'),
    sa.ForeignKeyConstraint(['ctxsg_province'], [u'cartix_province.ctxp_id'], name=u'cartix_savinggroup_ctxsg_province_fkey'),
    sa.ForeignKeyConstraint(['ctxsg_sector'], [u'cartix_sector.ctxs_id'], name=u'cartix_savinggroup_ctxsg_sector_fkey'),
    sa.PrimaryKeyConstraint('ctxsg_id', name=u'cartix_savinggroup_pkey')
    )
    ### end Alembic commands ###
