"""empty message

Revision ID: c1e15b8ede1d
Revises: 7d33d780ba92
Create Date: 2016-10-21 11:23:47.595190

"""

# revision identifiers, used by Alembic.
revision = 'c1e15b8ede1d'
down_revision = '7d33d780ba92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartix_savinggroup', sa.Column('ctxsg_status', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartix_savinggroup', 'ctxsg_status')
    ### end Alembic commands ###
