"""empty message

Revision ID: e1237b819fd0
Revises: fa050c3be861
Create Date: 2016-10-24 17:58:40.297183

"""

# revision identifiers, used by Alembic.
revision = 'e1237b819fd0'
down_revision = 'fa050c3be861'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartix_mfi', 'ctxm_gg')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartix_mfi', sa.Column('ctxm_gg', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
