"""empty message

Revision ID: fa050c3be861
Revises: 23bfe5eebc84
Create Date: 2016-10-24 17:58:15.867537

"""

# revision identifiers, used by Alembic.
revision = 'fa050c3be861'
down_revision = '23bfe5eebc84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartix_mfi', sa.Column('ctxm_gg', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartix_mfi', 'ctxm_gg')
    ### end Alembic commands ###
